#!/bin/bash

# --- Default Values ---
# Make all .sh files in those directories executable
chmod +x "${PIPELINE_DIR}/config"/*.sh
chmod +x "${PIPELINE_DIR}/config/hpc_helpers/"/*.sh
chmod +x "${PIPELINE_DIR}/anatomical"/*.sh
chmod +x "${PIPELINE_DIR}/functional"/*.sh
export PATH="${PIPELINE_DIR}/config/hpc_helpers:${PATH}"
export PATH="${PIPELINE_DIR}/config:${PATH}"
export PATH="${PIPELINE_DIR}/config/hpc_helpers:${PATH}"
export PATH="${PIPELINE_DIR}/anatomical:${PATH}"
export PATH="${PIPELINE_DIR}/functional:${PATH}"
# If PC_LOCATION is not set, default to "local"
[[ -z "$PC_LOCATION" ]] &&  export PC_LOCATION="local" 
# --- Software versions ---
export FREESURFER_VERSION="7.3.2"
export FSLICENSE="${PIPELINE_DIR}/config/license.txt"
export FSL_VERSION="6.0.7.19"

# --- CONTAINER SETTINGS ---
# -> docker 
export CONTAINER_TYPE="docker" # or singularity -> replace "docker" with "singularity "
export DOCKFILE_DIR="${PIPELINE_DIR}/dockfiles"
if [ ! -d "$DOCKFILE_DIR" ]; then
    mkdir -p "$DOCKFILE_DIR"
fi

export NEURODOCKER_VERSION="2.1.1" 
export FPREP_VERSION="25.2.4"
export AFNI_IMAGE="vnmd/afni_26.0.07"
export NIGHRES_IMAGE=gianfrancof0/nighres:latest #vnmd/nighres_1.5.2"
export NEURODOCKER_IMAGE="repronim/neurodocker:${NEURODOCKER_VERSION}"
export FPREP_IMAGE="nipreps/fmriprep:${FPREP_VERSION}"
export FSL_FREESURFER_IMAGE="ndock_fsl_freesurfer:latest" # <-- built locally from Dockerfile generated by neurodocker

# -> Singularity / apptainer
export SIF_DIR="${HOME}/Scratch/sifs/"
[[ ! -d "$SIF_DIR" ]] && mkdir -p "$SIF_DIR"
export SIF_DIR_LOCAL="${PIPELINE_DIR}/siffiles"
[[ ! -d "$SIF_DIR_LOCAL" ]] && mkdir -p "$SIF_DIR_LOCAL"
export NEURODOCKER_SIF="neurodocker-${NEURODOCKER_VERSION}.sif"
export FPREP_SIF="fmriprep-${FPREP_VERSION}.sif"
export AFNI_SIF="afni-26.0.07.sif"
export NIGHRES_SIF="nighres-latest.sif"
export FSL_FREESURFER_SIF="fsl_freesurfer.sif"


# --- Conda environments ---
export PYPACKAGE_MANAGER="mamba"
export NEUROPYTHY_VERSION="0.12.16"
export AUTOFLAT_VERSION="1.0.6"
export NIBABEL_VERSION="5.3.3"
export PYTHON_FOR_PIPELINE="3.11"
export NIPYPE_VERSION="1.10.0"
export ANTS_VERSION="0.6.3"
export NILEARN_VERSION="0.13.1"
export PYCTX_VERSION="1.3.0"


# --- PROJECT INFORMATION ---
source $PIPELINE_DIR/config/project_current.sh